from tkinter import * 
from PIL import ImageTk,Image
import payment
arr=[]
def but(sea):   
    if(sea['bg']== "white"):
       sea.config(bg="#CEA408")
       arr.append(sea['text'])        
    else:
        sea.config(bg="white")
        if(sea["text"] in arr):
            arr.remove(sea['text'])

def seat(na):
    #print(na)
    def pt():
        #print(arr)
        screen.destroy()
        payment.pay_s(arr,na)
        
    #payment.pay_s(5)
    name=na
    #print(name)

    screen=Tk()
    screen.geometry("1025x530")
    screen.config(bg="black")
    screen.iconbitmap(default='image/dragon.ico')
    screen.title("SELECT SEAT")

    #Labels
    Label(screen,text="SCREEN ON THIS SIDE",font=("Arial",18),padx=410,pady=20).grid(row=0,column=0,pady=20,columnspan=25)

    Label(screen,text="A",bg="black",fg='grey').grid(row=1,column=0,pady=20,padx=10)
    Label(screen,text="B",bg="black",fg='grey').grid(row=2,column=0,pady=20)
    Label(screen,text="C",bg="black",fg='grey').grid(row=3,column=0,pady=20)
    Label(screen,text="D",bg="black",fg='grey').grid(row=4,column=0,pady=20)
    Label(screen,text="E",bg="black",fg='grey').grid(row=5,column=0,pady=20)
    
    Label(screen,text="A",bg="black",fg='grey').grid(row=1,column=13,pady=20,padx=10)
    Label(screen,text="B",bg="black",fg='grey').grid(row=2,column=13,pady=20,padx=10)
    Label(screen,text="C",bg="black",fg='grey').grid(row=3,column=13,pady=20,padx=10)
    Label(screen,text="D",bg="black",fg='grey').grid(row=4,column=13,pady=20,padx=10)
    Label(screen,text="E",bg="black",fg='grey').grid(row=5,column=13,pady=20,padx=10)

    #Buttons
    a1=Button(screen,text='A1',padx=25,bg="white",command=lambda:but(a1))
    a1.grid(row=1,column=1)
    a2=Button(screen,text='A2',padx=25,bg="white",command=lambda:but(a2))
    a2.grid(row=1,column=2)
    Label(screen,text='',bg='black',padx=30).grid(row=1,column=3)
    a3=Button(screen,text='A3',padx=25,bg="white",command=lambda:but(a3))
    a3.grid(row=1,column=4)
    a4=Button(screen,text='A4',padx=25,bg="white",command=lambda:but(a4))
    a4.grid(row=1,column=5)
    a5=Button(screen,text='A5',padx=25,bg="white",command=lambda:but(a5))
    a5.grid(row=1,column=6)
    a6=Button(screen,text='A6',padx=25,bg="white",command=lambda:but(a6))
    a6.grid(row=1,column=7)
    a7=Button(screen,text='A7',padx=25,bg="white",command=lambda:but(a7))
    a7.grid(row=1,column=8)
    a8=Button(screen,text='A8',padx=25,bg="white",command=lambda:but(a8))
    a8.grid(row=1,column=9)
    Label(screen,text='',bg='black',padx=30).grid(row=1,column=10)
    a9=Button(screen,text='A9',padx=25,bg="white",command=lambda:but(a9))
    a9.grid(row=1,column=11)
    a10=Button(screen,text='A10',padx=25,bg="white",command=lambda:but(a10))
    a10.grid(row=1,column=12)

    b1=Button(screen,text='B1',padx=25,bg="white",command=lambda:but(b1))
    b1.grid(row=2,column=1)
    b2=Button(screen,text='B2',padx=25,bg="white",command=lambda:but(b2))
    b2.grid(row=2,column=2)
    Label(screen,text='',bg='black',padx=30).grid(row=2,column=3)
    b3=Button(screen,text='B3',padx=25,bg="white",command=lambda:but(b3))
    b3.grid(row=2,column=4)
    b4=Button(screen,text='B4',padx=25,bg="white",command=lambda:but(b4))
    b4.grid(row=2,column=5)
    b5=Button(screen,text='B5',padx=25,bg="white",command=lambda:but(b5))
    b5.grid(row=2,column=6)
    b6=Button(screen,text='B6',padx=25,bg="white",command=lambda:but(b6))
    b6.grid(row=2,column=7)
    b7=Button(screen,text='B7',padx=25,bg="white",command=lambda:but(b7))
    b7.grid(row=2,column=8)
    b8=Button(screen,text='B8',padx=25,bg="white",command=lambda:but(b8))
    b8.grid(row=2,column=9)
    Label(screen,text='',bg='black',padx=30).grid(row=2,column=10)
    b9=Button(screen,text='B9',padx=25,bg="white",command=lambda:but(b9))
    b9.grid(row=2,column=11)
    b10=Button(screen,text='B10',padx=25,bg="white",command=lambda:but(b10))
    b10.grid(row=2,column=12)

    c1=Button(screen,text='C1',padx=25,bg="white",command=lambda:but(c1))
    c1.grid(row=3,column=1)
    c2=Button(screen,text='C2',padx=25,bg="white",command=lambda:but(c2))
    c2.grid(row=3,column=2)
    Label(screen,text='',bg='black',padx=30).grid(row=3,column=3)
    c3=Button(screen,text='C3',padx=25,bg="white",command=lambda:but(c3))
    c3.grid(row=3,column=4)
    c4=Button(screen,text='C4',padx=25,bg="white",command=lambda:but(c4))
    c4.grid(row=3,column=5)
    c5=Button(screen,text='C5',padx=25,bg="white",command=lambda:but(c5))
    c5.grid(row=3,column=6)
    c6=Button(screen,text='C6',padx=25,bg="white",command=lambda:but(c6))
    c6.grid(row=3,column=7)
    c7=Button(screen,text='C7',padx=25,bg="white",command=lambda:but(c7))
    c7.grid(row=3,column=8)
    c8=Button(screen,text='C8',padx=25,bg="white",command=lambda:but(c8))
    c8.grid(row=3,column=9)
    Label(screen,text='',bg='black',padx=30).grid(row=3,column=10)
    c9=Button(screen,text='C9',padx=25,bg="white",command=lambda:but(c9))
    c9.grid(row=3,column=11)
    c10=Button(screen,text='C10',padx=25,bg="white",command=lambda:but(c10))
    c10.grid(row=3,column=12)

    d1=Button(screen,text='D1',padx=25,bg="white",command=lambda:but(d1))
    d1.grid(row=4,column=1)
    d2=Button(screen,text='D2',padx=25,bg="white",command=lambda:but(d2))
    d2.grid(row=4,column=2)
    Label(screen,text='',bg='black',padx=30).grid(row=4,column=3)
    d3=Button(screen,text='D3',padx=25,bg="white",command=lambda:but(d3))
    d3.grid(row=4,column=4)
    d4=Button(screen,text='D4',padx=25,bg="white",command=lambda:but(d4))
    d4.grid(row=4,column=5)
    d5=Button(screen,text='D5',padx=25,bg="white",command=lambda:but(d5))
    d5.grid(row=4,column=6)
    d6=Button(screen,text='D6',padx=25,bg="white",command=lambda:but(d6))
    d6.grid(row=4,column=7)
    d7=Button(screen,text='D7',padx=25,bg="white",command=lambda:but(d7))
    d7.grid(row=4,column=8)
    d8=Button(screen,text='D8',padx=25,bg="white",command=lambda:but(d8))
    d8.grid(row=4,column=9)
    Label(screen,text='',bg='black',padx=30).grid(row=4,column=10)
    d9=Button(screen,text='D9',padx=25,bg="white",command=lambda:but(d9))
    d9.grid(row=4,column=11)
    d10=Button(screen,text='D10',padx=25,bg="white",command=lambda:but(d10))
    d10.grid(row=4,column=12)

    e1=Button(screen,text='E1',padx=25,bg="white",command=lambda:but(e1))
    e1.grid(row=5,column=1)
    e2=Button(screen,text='E2',padx=25,bg="white",command=lambda:but(e2))
    e2.grid(row=5,column=2)
    Label(screen,text='',bg='black',padx=30).grid(row=5,column=3)
    e3=Button(screen,text='E3',padx=25,bg="white",command=lambda:but(e3))
    e3.grid(row=5,column=4)
    e4=Button(screen,text='E4',padx=25,bg="white",command=lambda:but(e4))
    e4.grid(row=5,column=5)
    e5=Button(screen,text='E5',padx=25,bg="white",command=lambda:but(e5))
    e5.grid(row=5,column=6)
    e6=Button(screen,text='E6',padx=25,bg="white",command=lambda:but(e6))
    e6.grid(row=5,column=7)
    e7=Button(screen,text='E7',padx=25,bg="white",command=lambda:but(e7))
    e7.grid(row=5,column=8)
    e8=Button(screen,text='E8',padx=25,bg="white",command=lambda:but(e8))
    e8.grid(row=5,column=9)
    Label(screen,text='',bg='black',padx=30).grid(row=5,column=10)
    e9=Button(screen,text='E9',padx=25,bg="white",command=lambda:but(e9))
    e9.grid(row=5,column=11)
    e10=Button(screen,text='E10',padx=25,bg="white",command=lambda:but(e10))
    e10.grid(row=5,column=12)

    c=Button(screen,text="confirm",font=("Arial",12),padx=20,pady=4,bg="black",fg="red",activebackground="black",activeforeground="red",command=pt).grid(row=6,column=11,pady=30,columnspan=5)
    

    screen.mainloop()

#seat("sai") 
